---

- name: Ensure homebrew packages are installed.
  hosts: localhost
  tasks: 
  - homebrew:
      name: bat
      state: latest

- name: Ensure git installed.
  hosts: localhost
  tasks:
  - package:
      name: git
      state: latest